In [10]:
# resolve imports
import numpy as np
import pandas as pd
from route_distance import AmenityDistanceCalculator

superset_amenities = ['parking', 'restaurant', 'fire_station', 'cinema', 'dentist',
       'school', 'atm', 'fuel', 'fast_food', 'toilets', 'pharmacy',
       'bank', 'police', 'post_box', 'place_of_worship', 'bar', 'pub',
       'cafe', 'clinic', 'hospital', 'community_centre',
       'vending_machine', 'bus_station', 'health_post', 'college',
       'theatre', 'showroom', 'marketplace']

In [11]:
# load the data
df = pd.read_csv('training_data.csv')
df = df.drop(columns='Unnamed: 0')
df

        Average Price   Latitude  Longitude
0                3829  17.308545  78.127204
1                3558  17.304148  78.126802
2                3838  17.307087  78.138482
3                2980  17.313139  78.140455
4                3067  17.306494  78.123479
...               ...        ...        ...
11845          198465  17.429253  78.450841
11846          197825  17.429651  78.423834
11847          198337  17.428891  78.431225
11848          198623  17.418291  78.425544
11849          198253  17.410243  78.428087

[11850 rows x 3 columns]

In [23]:
# import merged_data
new_df = pd.read_csv('merged_data.csv')
new_df

         Locality   Average Price   Latitude  Longitude
0        Chevella            3462  17.313103  78.137523
1      Bhuvangiri            6483  17.505096  78.881987
2       Shadnagar            8906  17.068916  78.207226
3       Ghatkesar            9770  17.452694  78.681166
4     Maheshwaram           13268  17.134372  78.432225
..            ...             ...        ...        ...
74   Nanakramguda          102581  17.416302  78.343114
75        Kokapet          155000  17.394735  78.337281
76     Hitec City          158813  17.446384  78.376659
77  Jubilee Hills          194414  17.430695  78.406081
78  Banjara Hills          198169  17.416385  78.436884

[79 rows x 4 columns]

In [29]:
# Assuming 'Latitude' and 'Longitude' columns are present in new_df
for index, row in new_df.iterrows():
    # Create an instance of AmenityDistanceCalculator for each row
    dist = AmenityDistanceCalculator(row['Latitude'], row['Longitude'], radius=2000)
    
    # Calculate distances
    distances_df = dist.calculate_distances((row['Latitude'], row['Longitude']))
    
    # Map the distances back to the original DataFrame (df)
    for amenity in superset_amenities:
        # Check if the amenity is present in distances_df
        if amenity in distances_df['Amenity'].values:
            # Map the distance to the corresponding row and column
            new_df.at[index, amenity] = distances_df.loc[distances_df['Amenity'] == amenity, 'Amenity_distance_From_point'].values[0]
        else:
            # If amenity is not present, mark as 0
            new_df.at[index, amenity] = 0

# Display the updated DataFrame (df)
new_df

c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns

InsufficientResponseError: No data elements in server response. Check log and query location/tags.

In [30]:
new_df

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,1744.302929,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.0,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.0,0.0,0.00000,1119.744442,0.0,7983.616491,0.000000,0.0,0.0,27670.62714,26106.333083,0.000000,0.000000,1320.153624,0.00000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.0,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.0,0.0,452.30992,0.000000,0.0,1826.029178,282.440013,0.0,0.0,0.00000,4400.326045,11098.419346,1858.786022,303.854685,707.58961,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.0,0.000000,0.000000,0.000000,646.930797,1512.309022,0.0,0.0,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,2528.387110,0.000000,0.000000,0.000000,0.00000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Nanakramguda,102581,17.416302,78.343114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Kokapet,155000,17.394735,78.337281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Hitec City,158813,17.446384,78.376659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Jubilee Hills,194414,17.430695,78.406081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Banjara Hills,198169,17.416385,78.436884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Assuming 'Latitude' and 'Longitude' columns are present in new_df
for index in range(len(new_df) - 1, -1, -1):
    row = new_df.iloc[index]
    # Create an instance of AmenityDistanceCalculator for each row
    dist = AmenityDistanceCalculator(row['Latitude'], row['Longitude'], radius=2000)
    
    # Calculate distances
    distances_df = dist.calculate_distances((row['Latitude'], row['Longitude']))
    
    # Map the distances back to the original DataFrame (df)
    for amenity in superset_amenities:
        # Check if the amenity is present in distances_df
        if amenity in distances_df['Amenity'].values:
            # Map the distance to the corresponding row and column
            new_df.at[index, amenity] = distances_df.loc[distances_df['Amenity'] == amenity, 'Amenity_distance_From_point'].values[0]
        else:
            # If amenity is not present, mark as 0
            new_df.at[index, amenity] = 0

# Display the updated DataFrame (df)
new_df

c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns

InsufficientResponseError: No data elements in server response. Check log and query location/tags.

In [32]:
new_df

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.000000,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.000000,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Nanakramguda,102581,17.416302,78.343114,13220.912950,11202.224985,0.0,0.000000,0.000000,2338.390996,3406.240690,3258.548690,8350.420658,3065.185507,6597.824915,6766.274936,0.000000,0.000000,755.685047,0.000000,6502.098538,3997.403907,0.000000,448.955479,2019.339611,0.000000,0.000000,532.505259,3863.653548,4297.943827,0.0,0.000000
75,Kokapet,155000,17.394735,78.337281,6986.081300,2500.368915,0.0,1066.522683,0.000000,3734.594509,0.000000,2618.143593,2439.805037,0.000000,1261.690863,2607.185224,0.000000,1885.631883,0.000000,0.000000,715.734402,1452.480213,2052.844928,0.000000,0.000000,0.000000,1813.895317,0.000000,5432.506584,0.000000,0.0,0.000000
76,Hitec City,158813,17.446384,78.376659,41486.304446,236694.068675,0.0,11528.085946,5958.647329,22852.414689,60545.034784,13326.518029,55996.481734,931.052428,30037.415163,58321.904980,5756.015154,0.000000,37369.852142,8109.434177,6500.468141,36174.466671,16367.785468,36072.021331,9638.884983,0.000000,0.000000,1282.157595,17172.479484,5975.088515,0.0,2250.014452
77,Jubilee Hills,194414,17.430695,78.406081,14465.712338,178560.389821,0.0,6421.783267,2416.885646,33193.793008,50170.746074,13155.800214,27697.436846,2995.493421,24370.564377,61397.255384,2923.510841,820.280859,51513.015230,8991.464058,9802.280500,31614.934475,8938.499616,44959.300543,5946.694544,0.000000,4654.056355,8473.615458,10152.867282,6126.009828,0.0,0.000000
78,Banjara Hills,198169,17.416385,78.436884,14431.430012,105862.626933,0.0,15200.607657,0.000000,16494.033535,37953.461081,8146.230164,26596.279741,0.000000,13883.639624,37060.698333,2651.407212,2130.283513,33876.611304,6092.077424,2916.201113,17958.275815,15955.320557,107266.281859,1949.016073,0.000000,2067.683210,9049.523723,7360.860574,5093.329191,0.0,784.883104

In [35]:
# Assuming 'Latitude' and 'Longitude' columns are present in new_df
total_rows = len(new_df)
middle_index = total_rows // 2

for index in range(middle_index, -1, -1):
    row = new_df.iloc[index]
    # Create an instance of AmenityDistanceCalculator for each row
    dist = AmenityDistanceCalculator(row['Latitude'], row['Longitude'], radius=2000)
    
    # Calculate distances
    distances_df = dist.calculate_distances((row['Latitude'], row['Longitude']))
    
    # Map the distances back to the original DataFrame (df)
    for amenity in superset_amenities:
        # Check if the amenity is present in distances_df
        if amenity in distances_df['Amenity'].values:
            # Map the distance to the corresponding row and column
            new_df.at[index, amenity] = distances_df.loc[distances_df['Amenity'] == amenity, 'Amenity_distance_From_point'].values[0]
        else:
            # If amenity is not present, mark as 0
            new_df.at[index, amenity] = 0

# Display the updated DataFrame (df)
new_df

c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns

InsufficientResponseError: No data elements in server response. Check log and query location/tags.

In [38]:
# Assuming 'Latitude' and 'Longitude' columns are present in new_df
total_rows = len(new_df)

for index in range(total_rows - 1, -1, -5):
    row = new_df.iloc[index]
    # Create an instance of AmenityDistanceCalculator for each row
    dist = AmenityDistanceCalculator(row['Latitude'], row['Longitude'], radius=2000)
    
    # Calculate distances
    distances_df = dist.calculate_distances((row['Latitude'], row['Longitude']))
    
    # Map the distances back to the original DataFrame (df)
    for amenity in superset_amenities:
        # Check if the amenity is present in distances_df
        if amenity in distances_df['Amenity'].values:
            # Map the distance to the corresponding row and column
            new_df.at[index, amenity] = distances_df.loc[distances_df['Amenity'] == amenity, 'Amenity_distance_From_point'].values[0]
        else:
            # If amenity is not present, mark as 0
            new_df.at[index, amenity] = 0

# Display the updated DataFrame (df)
new_df

c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.000000,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.000000,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Nanakramguda,102581,17.416302,78.343114,13220.912950,11202.224985,0.0,0.000000,0.000000,2338.390996,3406.240690,3258.548690,8350.420658,3065.185507,6597.824915,6766.274936,0.000000,0.000000,755.685047,0.000000,6502.098538,3997.403907,0.000000,448.955479,2019.339611,0.000000,0.000000,532.505259,3863.653548,4297.943827,0.0,0.000000
75,Kokapet,155000,17.394735,78.337281,6986.081300,2500.368915,0.0,1066.522683,0.000000,3734.594509,0.000000,2618.143593,2439.805037,0.000000,1261.690863,2607.185224,0.000000,1885.631883,0.000000,0.000000,715.734402,1452.480213,2052.844928,0.000000,0.000000,0.000000,1813.895317,0.000000,5432.506584,0.000000,0.0,0.000000
76,Hitec City,158813,17.446384,78.376659,41486.304446,236694.068675,0.0,11528.085946,5958.647329,22852.414689,60545.034784,13326.518029,55996.481734,931.052428,30037.415163,58321.904980,5756.015154,0.000000,37369.852142,8109.434177,6500.468141,36174.466671,16367.785468,36072.021331,9638.884983,0.000000,0.000000,1282.157595,17172.479484,5975.088515,0.0,2250.014452
77,Jubilee Hills,194414,17.430695,78.406081,14465.712338,178560.389821,0.0,6421.783267,2416.885646,33193.793008,50170.746074,13155.800214,27697.436846,2995.493421,24370.564377,61397.255384,2923.510841,820.280859,51513.015230,8991.464058,9802.280500,31614.934475,8938.499616,44959.300543,5946.694544,0.000000,4654.056355,8473.615458,10152.867282,6126.009828,0.0,0.000000
78,Banjara Hills,198169,17.416385,78.436884,14431.430012,105862.626933,0.0,15200.607657,0.000000,16494.033535,37953.461081,8146.230164,26596.279741,0.000000,13883.639624,37060.698333,2651.407212,2130.283513,33876.611304,6092.077424,2916.201113,17958.275815,15955.320557,107266.281859,1949.016073,0.000000,2067.683210,9049.523723,7360.860574,5093.329191,0.0,784.883104

In [44]:
# Assuming 'Latitude' and 'Longitude' columns are present in new_df
for index, row in new_df.iterrows():
    # Check if all elements in the row, excluding 'Latitude' and 'Longitude', are zero
    if row.drop(['Latitude', 'Longitude', 'Locality', ' Average Price']).isna().all():
        # Create an instance of AmenityDistanceCalculator for each row
        dist = AmenityDistanceCalculator(row['Latitude'], row['Longitude'], radius=2000)
        
        # Calculate distances
        distances_df = dist.calculate_distances((row['Latitude'], row['Longitude']))
        
        # Map the distances back to the original DataFrame (df)
        for amenity in superset_amenities:
            # Check if the amenity is present in distances_df
            if amenity in distances_df['Amenity'].values:
                # Map the distance to the corresponding row and column
                new_df.at[index, amenity] = distances_df.loc[distances_df['Amenity'] == amenity, 'Amenity_distance_From_point'].values[0]
            else:
                # If amenity is not present, mark as 0
                new_df.at[index, amenity] = 0

# Display the updated DataFrame (df)
new_df

c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns

InsufficientResponseError: No data elements in server response. Check log and query location/tags.

In [43]:
new_df.head(50)

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.000000,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.0,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.000000,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.0,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
5,Adibatla,13598,17.234396,78.541421,24898.290171,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
6,Sadashivpet,14412,17.618054,77.953249,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5322.840019,0.000000,0.0,0.000000,726.248628,0.000000,0.000000,0.000000,289.971932,375.938183,0.000000,0.000000,0.0,0.000000
7,Kothur,15355,17.145578,78.290648,531.751106,355.493671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,393.277112,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,537.822194,0.000000,0.000000,0.000000,0.000000,275.981755,0.000000,0.000000,0.0,0.000000
8,Moinabad,17219,17.326152,78.273584,4055.183278,2742.998841,0.000000,0.000000,0.000000,0.000000,0.000000,1358.628412,2040.404327,0.000000,0.000000,611.236499,0.000000,0.000000,918.390920,0.000000,0.0,2046.857244,657.951981,2340.912136,0.000000,0.000000,0.000000,2203.351623,3969.415339,1961.539209,0.0,0.000000
9,Bibinagar,17273,7.470609,78.797305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Keesara,18243,17.523576,78.663620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rudraram,18312,17.562141,78.167158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Sangareddy,18446,17.613189,78.080833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Medchal,18651,17.634638,78.485877,0.000000,3773.719338,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4454.661791,0.000000,0.0,0.000000,1683.397117,0.000000,0.000000,0.000000,50.533589,1513.877738,0.000000,0.000000,0.0,0.000000
14,Nandigama,19296,17.505829,78.199878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Isnapur,19345,17.547515,78.206332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Kongara Kalan,19858,17.198871,78.550229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Tukkuguda,21549,17.209089,78.476254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Kuntloor,22475,17.338030,78.626753,6074.474635,0.000000,0.000000,0.000000,0.000000,4542.813370,0.000000,4594.283855,0.000000,0.000000,288.448838,0.000000,0.000000,0.000000,8832.508991,0.000000,0.0,0.000000,0.000000,0.000000,2177.153609,0.000000,0.000000,0.000000,2816.579835,0.000000,0.0,0.000000
19,Shamirpet,23158,17.585124,78.574297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Rampally,24026,17.465950,78.638261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Bhanoor,24043,17.474855,78.169181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Sultanpur,24153,17.555490,78.308970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Chandrayanagutta,24387,17.304174,78.471362,0.000000,0.000000,0.000000,0.000000,0.000000,1849.432843,0.000000,4064.605075,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3545.156314,0.000000,0.0,0.000000,819.983881,367.345603,4293.707769,0.000000,0.000000,1958.879291,8439.909885,0.000000,0.0,0.000000
24,Kardhanur,25109,17.513889,78.230624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Shankarpally,25582,17.458760,78.132410,0.000000,0.000000,0.000000,0.000000,0.000000,283.634709,0.000000,1018.051360,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1030.288787,0.000000,0.0,0.000000,952.150592,383.781936,0.000000,0.000000,355.044283,2099.946058,0.000000,0.000000,0.0,0.000000
26,Ibrahimpatnam,27522,17.191018,78.648168,0.000000,0.000000,0.000000,431.647054,0.000000,0.000000,0.000000,2458.884099,0.000000,0.000000,0.000000,0.000000,370.205546,0.000000,6867.796981,0.000000,0.0,0.000000,0.000000,1003.952343,0.000000,0.000000,576.977727,0.000000,0.000000,0.000000,0.0,0.000000
27,Turkayamjal,28743,17.271266,78.581811,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1489.605554,0.000000,0.0,0.000000,0.000000,1477.359273,0.000000,0.000000,0.000000,1190.584592,0.000000,0.000000,0.0,0.000000
28,Patancheru,28858,17.525497,78.266884,0.000000,431.013407,0.000000,839.191064,0.000000,6832.091596,0.000000,346.374583,574.231330,0.000000,631.295627,2969.787506,1027.064987,0.000000,8220.732278,817.891968,0.0,593.768756,7773.489368,3092.247659,0.000000,0.000000,463.801987,10308.347906,1367.077717,782.708774,0.0,2631.426311
29,Patighanpur,28874,17.525497,78.266884,0.000000,431.013407,0.000000,839.191064,0.000000,6832.091596,0.000000,346.374583,574.231330,0.000000,631.295627,2969.787506,1027.064987,0.000000,8220.732278,817.891968,0.0,593.768756,7773.489368,3092.247659,0.000000,0.000000,463.801987,10308.347906,1367.077717,782.708774,0.0,2631.426311
30,Nadargul,29344,17.277521,78.549815,2341.416003,1184.060211,0.000000,0.000000,0.000000,1072.866055,0.000000,0.000000,0.000000,0.000000,0.000000,1386.881131,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1201.831887,0.000000,0.000000,0.000000,434.680524,2388.296738,0.000000,0.0,0.000000
31,Gundlapochampalli,32199,17.587805,78.415060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1877.742471,0.000000,0.000000,0.000000,2859.428378,0.000000,0.000000,0.000000,0.000000,0.0,2652.530660,1497.475905,0.000000,1917.528862,0.000000,0.000000,0.000000,6547.874439,0.000000,0.0,0.000000
32,Narapally,32213,17.425059,78.621171,0.000000,7889.430950,0.000000,0.000000,0.000000,7411.606943,2403.807029,3569.559875,1657.341859,0.000000,0.000000,3756.360334,0.000000,0.000000,0.000000,5060.421893,0.0,1118.001747,3421.138348,3680.930724,4864.633303,3350.521149,1338.873687,2111.946150,4962.813182,0.000000,0.0,0.000000
33,Muthangi,32344,17.540567,78.226557,0.000000,1217.900932,0.000000,0.000000,0.000000,3145.062118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4568.336136,0.000000,0.0,0.000000,1508.177642,3573.955963,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
34,Shamshabad,32540,17.260180,78.394604,0.000000,816.396781,0.000000,0.000000,0.000000,0.000000,0.000000,1317.973988,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,3661.614978,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
35,Gajularamaram,32583,17.534308,78.405518,8747.376815,8062.163173,0.000000,0.000000,3779.494903,19507.736315,10989.389678,11519.150826,7483.374776,0.000000,7035.007031,10941.903227,0.000000,0.000000,11465.861057,0.000000,0.0,0.000000,4713.967943,3972.202595,2740.213711,0.000000,1819.898023,0.000000,6384.433491,0.000000,0.0,1490.495852
36,Hayathnagar,33798,17.325128,78.602836,1994.811518,2758.532791,0.000000,0.000000,0.000000,3591.522978,5206.316860,4491.877450,1655.390169,356.106142,0.000000,6608.379892,276.360790,0.000000,16371.120103,0.000000,0.0,0.000000,1131.655915,2780.456738,3142.104851,0.000000,1934.091101,476.555336,1278.839403,0.000000,0.0,0.000000
37,Cherlapalli,34059,17.463773,78.594822,0.000000,5463.227201,0.000000,0.000000,0.000000,4433.418332,967.277613,5069.907171,0.000000,0.000000,0.000000,2980.826072,0.000000,0.000000,2773.070165,0.000000,0.0,0.000000,3955.167783,1995.526123,0.000000,0.000000,0.000000,4986.124070,0.000000,0.000000,0.0,0.000000
38,Beeramguda,34368,17.517752,78.300880,966.218613,7909.639426,0.000000,1585.387507,828.460306,13955.135981,0.000000,4794.706464,2409.938278,3174.319735,672.520642,5161.987677,0.000000,0.000000,18926.038292,1264.361198,0.0,0.000000,10128.067529,10797.538398,2881.615460,0.000000,3662.861843,21193.361816,0.000000,5853.057428,0.0,2110.160223
39,Gandi Maisamma,34583,17.575024,78.424495,0.000000,2251.302439,0.000000,0.000000,0.000000,0.000000,0.000000,3699.091947,0.000000,0.000000,0.000000,3186.530679,0.000000,0.000000,2196.550002,0.000000,0.0,953.637205,4675.993577,0.000000,580.068082,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
40,Ameenpur,35431,17.527878,78.328244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Boduppal,43168,17.414001,78.582708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Kollur,45300,13.863416,74.813483,196.922312,0.000000,0.000000,0.000000,0.000000,338.798809,365.798455,0.000000,592.510755,415.830261,157.416966,142.305685,11.666667,295.534611,1915.376155,0.000000,0.0,0.000000,0.000000,0.000000,220.660373,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
43,Kapra,46936,17.488273,78.574072,0.000000,29450.225169,0.000000,6779.812287,0.000000,6427.590201,5776.266777,11335.323501,9835.552412,1448.025332,3965.850340,9273.122931,1759.458611,0.000000,25691.503881,6476.320265,0.0,0.000000,842.202224,27884.798292,4817.749326,0.000000,1805.451062,14983.104226,1597.014773,2866.193420,0.0,876.493243
44,Bachupally,47296,17.550005,78.384974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Bolarum,48248,17.518742,78.510851,2156.451888,0.000000,0.000000,804.291163,0.000000,4860.963317,2685.488937,2911.628905,0.000000,0.000000,1182.472883,1423.491403,1637.034097,0.000000,9887.945512,0.000000,0.0,4248.872537,1804.506236,8046.867140,0.000000,0.000000,0.000000,622.445991,0.000000,809.014108,0.0,1464.357121
46,Alwal,48622,17.499156,78.496013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Appa Junction,48879,17.349799,78.359585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Rajendra Nagar,52140,28.638322,77.181302,0.000000,10274.710519,1575.246601,0.000000,0.000000,59730.823064,13837.192337,8768.447367,17959.118663,5069.476229,0.000000,26510.794126,4294.937898,5082.652194,13330.100440,0.000000,0.0,3339.318517,20091.947865,19924.943245,0.000000,0.000000,736.212114,0.000000,4233.739116,0.000000,0.0,68.009333
49,Miyapur,52725,17.514392,78.343342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
new_df['Latitude'][9] = 17.470609
new_df.head(50)

C:\Users\HP\AppData\Local\Temp\ipykernel_15420\2851019120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Latitude'][9] = 17.470609

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.000000,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.0,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.000000,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.0,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
5,Adibatla,13598,17.234396,78.541421,24898.290171,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
6,Sadashivpet,14412,17.618054,77.953249,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5322.840019,0.000000,0.0,0.000000,726.248628,0.000000,0.000000,0.000000,289.971932,375.938183,0.000000,0.000000,0.0,0.000000
7,Kothur,15355,17.145578,78.290648,531.751106,355.493671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,393.277112,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,537.822194,0.000000,0.000000,0.000000,0.000000,275.981755,0.000000,0.000000,0.0,0.000000
8,Moinabad,17219,17.326152,78.273584,4055.183278,2742.998841,0.000000,0.000000,0.000000,0.000000,0.000000,1358.628412,2040.404327,0.000000,0.000000,611.236499,0.000000,0.000000,918.390920,0.000000,0.0,2046.857244,657.951981,2340.912136,0.000000,0.000000,0.000000,2203.351623,3969.415339,1961.539209,0.0,0.000000
9,Bibinagar,17273,17.470609,78.797305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Keesara,18243,17.523576,78.663620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rudraram,18312,17.562141,78.167158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Sangareddy,18446,17.613189,78.080833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Medchal,18651,17.634638,78.485877,0.000000,3773.719338,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4454.661791,0.000000,0.0,0.000000,1683.397117,0.000000,0.000000,0.000000,50.533589,1513.877738,0.000000,0.000000,0.0,0.000000
14,Nandigama,19296,17.505829,78.199878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Isnapur,19345,17.547515,78.206332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Kongara Kalan,19858,17.198871,78.550229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Tukkuguda,21549,17.209089,78.476254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Kuntloor,22475,17.338030,78.626753,6074.474635,0.000000,0.000000,0.000000,0.000000,4542.813370,0.000000,4594.283855,0.000000,0.000000,288.448838,0.000000,0.000000,0.000000,8832.508991,0.000000,0.0,0.000000,0.000000,0.000000,2177.153609,0.000000,0.000000,0.000000,2816.579835,0.000000,0.0,0.000000
19,Shamirpet,23158,17.585124,78.574297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Rampally,24026,17.465950,78.638261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Bhanoor,24043,17.474855,78.169181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Sultanpur,24153,17.555490,78.308970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Chandrayanagutta,24387,17.304174,78.471362,0.000000,0.000000,0.000000,0.000000,0.000000,1849.432843,0.000000,4064.605075,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3545.156314,0.000000,0.0,0.000000,819.983881,367.345603,4293.707769,0.000000,0.000000,1958.879291,8439.909885,0.000000,0.0,0.000000
24,Kardhanur,25109,17.513889,78.230624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Shankarpally,25582,17.458760,78.132410,0.000000,0.000000,0.000000,0.000000,0.000000,283.634709,0.000000,1018.051360,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1030.288787,0.000000,0.0,0.000000,952.150592,383.781936,0.000000,0.000000,355.044283,2099.946058,0.000000,0.000000,0.0,0.000000
26,Ibrahimpatnam,27522,17.191018,78.648168,0.000000,0.000000,0.000000,431.647054,0.000000,0.000000,0.000000,2458.884099,0.000000,0.000000,0.000000,0.000000,370.205546,0.000000,6867.796981,0.000000,0.0,0.000000,0.000000,1003.952343,0.000000,0.000000,576.977727,0.000000,0.000000,0.000000,0.0,0.000000
27,Turkayamjal,28743,17.271266,78.581811,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1489.605554,0.000000,0.0,0.000000,0.000000,1477.359273,0.000000,0.000000,0.000000,1190.584592,0.000000,0.000000,0.0,0.000000
28,Patancheru,28858,17.525497,78.266884,0.000000,431.013407,0.000000,839.191064,0.000000,6832.091596,0.000000,346.374583,574.231330,0.000000,631.295627,2969.787506,1027.064987,0.000000,8220.732278,817.891968,0.0,593.768756,7773.489368,3092.247659,0.000000,0.000000,463.801987,10308.347906,1367.077717,782.708774,0.0,2631.426311
29,Patighanpur,28874,17.525497,78.266884,0.000000,431.013407,0.000000,839.191064,0.000000,6832.091596,0.000000,346.374583,574.231330,0.000000,631.295627,2969.787506,1027.064987,0.000000,8220.732278,817.891968,0.0,593.768756,7773.489368,3092.247659,0.000000,0.000000,463.801987,10308.347906,1367.077717,782.708774,0.0,2631.426311
30,Nadargul,29344,17.277521,78.549815,2341.416003,1184.060211,0.000000,0.000000,0.000000,1072.866055,0.000000,0.000000,0.000000,0.000000,0.000000,1386.881131,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1201.831887,0.000000,0.000000,0.000000,434.680524,2388.296738,0.000000,0.0,0.000000
31,Gundlapochampalli,32199,17.587805,78.415060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1877.742471,0.000000,0.000000,0.000000,2859.428378,0.000000,0.000000,0.000000,0.000000,0.0,2652.530660,1497.475905,0.000000,1917.528862,0.000000,0.000000,0.000000,6547.874439,0.000000,0.0,0.000000
32,Narapally,32213,17.425059,78.621171,0.000000,7889.430950,0.000000,0.000000,0.000000,7411.606943,2403.807029,3569.559875,1657.341859,0.000000,0.000000,3756.360334,0.000000,0.000000,0.000000,5060.421893,0.0,1118.001747,3421.138348,3680.930724,4864.633303,3350.521149,1338.873687,2111.946150,4962.813182,0.000000,0.0,0.000000
33,Muthangi,32344,17.540567,78.226557,0.000000,1217.900932,0.000000,0.000000,0.000000,3145.062118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4568.336136,0.000000,0.0,0.000000,1508.177642,3573.955963,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
34,Shamshabad,32540,17.260180,78.394604,0.000000,816.396781,0.000000,0.000000,0.000000,0.000000,0.000000,1317.973988,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,3661.614978,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
35,Gajularamaram,32583,17.534308,78.405518,8747.376815,8062.163173,0.000000,0.000000,3779.494903,19507.736315,10989.389678,11519.150826,7483.374776,0.000000,7035.007031,10941.903227,0.000000,0.000000,11465.861057,0.000000,0.0,0.000000,4713.967943,3972.202595,2740.213711,0.000000,1819.898023,0.000000,6384.433491,0.000000,0.0,1490.495852
36,Hayathnagar,33798,17.325128,78.602836,1994.811518,2758.532791,0.000000,0.000000,0.000000,3591.522978,5206.316860,4491.877450,1655.390169,356.106142,0.000000,6608.379892,276.360790,0.000000,16371.120103,0.000000,0.0,0.000000,1131.655915,2780.456738,3142.104851,0.000000,1934.091101,476.555336,1278.839403,0.000000,0.0,0.000000
37,Cherlapalli,34059,17.463773,78.594822,0.000000,5463.227201,0.000000,0.000000,0.000000,4433.418332,967.277613,5069.907171,0.000000,0.000000,0.000000,2980.826072,0.000000,0.000000,2773.070165,0.000000,0.0,0.000000,3955.167783,1995.526123,0.000000,0.000000,0.000000,4986.124070,0.000000,0.000000,0.0,0.000000
38,Beeramguda,34368,17.517752,78.300880,966.218613,7909.639426,0.000000,1585.387507,828.460306,13955.135981,0.000000,4794.706464,2409.938278,3174.319735,672.520642,5161.987677,0.000000,0.000000,18926.038292,1264.361198,0.0,0.000000,10128.067529,10797.538398,2881.615460,0.000000,3662.861843,21193.361816,0.000000,5853.057428,0.0,2110.160223
39,Gandi Maisamma,34583,17.575024,78.424495,0.000000,2251.302439,0.000000,0.000000,0.000000,0.000000,0.000000,3699.091947,0.000000,0.000000,0.000000,3186.530679,0.000000,0.000000,2196.550002,0.000000,0.0,953.637205,4675.993577,0.000000,580.068082,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
40,Ameenpur,35431,17.527878,78.328244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Boduppal,43168,17.414001,78.582708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Kollur,45300,13.863416,74.813483,196.922312,0.000000,0.000000,0.000000,0.000000,338.798809,365.798455,0.000000,592.510755,415.830261,157.416966,142.305685,11.666667,295.534611,1915.376155,0.000000,0.0,0.000000,0.000000,0.000000,220.660373,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
43,Kapra,46936,17.488273,78.574072,0.000000,29450.225169,0.000000,6779.812287,0.000000,6427.590201,5776.266777,11335.323501,9835.552412,1448.025332,3965.850340,9273.122931,1759.458611,0.000000,25691.503881,6476.320265,0.0,0.000000,842.202224,27884.798292,4817.749326,0.000000,1805.451062,14983.104226,1597.014773,2866.193420,0.0,876.493243
44,Bachupally,47296,17.550005,78.384974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Bolarum,48248,17.518742,78.510851,2156.451888,0.000000,0.000000,804.291163,0.000000,4860.963317,2685.488937,2911.628905,0.000000,0.000000,1182.472883,1423.491403,1637.034097,0.000000,9887.945512,0.000000,0.0,4248.872537,1804.506236,8046.867140,0.000000,0.000000,0.000000,622.445991,0.000000,809.014108,0.0,1464.357121
46,Alwal,48622,17.499156,78.496013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Appa Junction,48879,17.349799,78.359585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Rajendra Nagar,52140,28.638322,77.181302,0.000000,10274.710519,1575.246601,0.000000,0.000000,59730.823064,13837.192337,8768.447367,17959.118663,5069.476229,0.000000,26510.794126,4294.937898,5082.652194,13330.100440,0.000000,0.0,3339.318517,20091.947865,19924.943245,0.000000,0.000000,736.212114,0.000000,4233.739116,0.000000,0.0,68.009333
49,Miyapur,52725,17.514392,78.343342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
# Assuming 'Latitude' and 'Longitude' columns are present in new_df
for index, row in new_df.iterrows():
    # Check if all elements in the row, excluding 'Latitude' and 'Longitude', are zero
    if row.drop(['Latitude', 'Longitude', 'Locality', ' Average Price']).isna().all():
        # Create an instance of AmenityDistanceCalculator for each row
        dist = AmenityDistanceCalculator(row['Latitude'], row['Longitude'], radius=2000)
        
        # Calculate distances
        distances_df = dist.calculate_distances((row['Latitude'], row['Longitude']))
        
        # Map the distances back to the original DataFrame (df)
        for amenity in superset_amenities:
            # Check if the amenity is present in distances_df
            if amenity in distances_df['Amenity'].values:
                # Map the distance to the corresponding row and column
                new_df.at[index, amenity] = distances_df.loc[distances_df['Amenity'] == amenity, 'Amenity_distance_From_point'].values[0]
            else:
                # If amenity is not present, mark as 0
                new_df.at[index, amenity] = 0

# Display the updated DataFrame (df)
new_df

c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns
c:\Users\HP\Desktop\EstateVerse-Geospatial-Model\Data Pre-processing\route_distance.py:23: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release.
  # Drop unnecessary columns

InsufficientResponseError: No data elements in server response. Check log and query location/tags.

In [50]:
# print all those rows which have NaN values
rows = new_df[new_df.isna().any(axis=1)]
rows

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
24,Kardhanur,25109,17.513889,78.230624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Ameenpur,35431,17.527878,78.328244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Boduppal,43168,17.414001,78.582708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Bachupally,47296,17.550005,78.384974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Alwal,48622,17.499156,78.496013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Appa Junction,48879,17.349799,78.359585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Miyapur,52725,17.514392,78.343342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Mokila,52947,17.435506,78.191985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
new_df

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.000000,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.000000,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Nanakramguda,102581,17.416302,78.343114,13220.912950,11202.224985,0.0,0.000000,0.000000,2338.390996,3406.240690,3258.548690,8350.420658,3065.185507,6597.824915,6766.274936,0.000000,0.000000,755.685047,0.000000,6502.098538,3997.403907,0.000000,448.955479,2019.339611,0.000000,0.000000,532.505259,3863.653548,4297.943827,0.0,0.000000
75,Kokapet,155000,17.394735,78.337281,6986.081300,2500.368915,0.0,1066.522683,0.000000,3734.594509,0.000000,2618.143593,2439.805037,0.000000,1261.690863,2607.185224,0.000000,1885.631883,0.000000,0.000000,715.734402,1452.480213,2052.844928,0.000000,0.000000,0.000000,1813.895317,0.000000,5432.506584,0.000000,0.0,0.000000
76,Hitec City,158813,17.446384,78.376659,41486.304446,236694.068675,0.0,11528.085946,5958.647329,22852.414689,60545.034784,13326.518029,55996.481734,931.052428,30037.415163,58321.904980,5756.015154,0.000000,37369.852142,8109.434177,6500.468141,36174.466671,16367.785468,36072.021331,9638.884983,0.000000,0.000000,1282.157595,17172.479484,5975.088515,0.0,2250.014452
77,Jubilee Hills,194414,17.430695,78.406081,14465.712338,178560.389821,0.0,6421.783267,2416.885646,33193.793008,50170.746074,13155.800214,27697.436846,2995.493421,24370.564377,61397.255384,2923.510841,820.280859,51513.015230,8991.464058,9802.280500,31614.934475,8938.499616,44959.300543,5946.694544,0.000000,4654.056355,8473.615458,10152.867282,6126.009828,0.0,0.000000
78,Banjara Hills,198169,17.416385,78.436884,14431.430012,105862.626933,0.0,15200.607657,0.000000,16494.033535,37953.461081,8146.230164,26596.279741,0.000000,13883.639624,37060.698333,2651.407212,2130.283513,33876.611304,6092.077424,2916.201113,17958.275815,15955.320557,107266.281859,1949.016073,0.000000,2067.683210,9049.523723,7360.860574,5093.329191,0.0,784.883104

In [51]:
new_df = new_df.dropna()
new_df

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.000000,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.000000,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Nanakramguda,102581,17.416302,78.343114,13220.912950,11202.224985,0.0,0.000000,0.000000,2338.390996,3406.240690,3258.548690,8350.420658,3065.185507,6597.824915,6766.274936,0.000000,0.000000,755.685047,0.000000,6502.098538,3997.403907,0.000000,448.955479,2019.339611,0.000000,0.000000,532.505259,3863.653548,4297.943827,0.0,0.000000
75,Kokapet,155000,17.394735,78.337281,6986.081300,2500.368915,0.0,1066.522683,0.000000,3734.594509,0.000000,2618.143593,2439.805037,0.000000,1261.690863,2607.185224,0.000000,1885.631883,0.000000,0.000000,715.734402,1452.480213,2052.844928,0.000000,0.000000,0.000000,1813.895317,0.000000,5432.506584,0.000000,0.0,0.000000
76,Hitec City,158813,17.446384,78.376659,41486.304446,236694.068675,0.0,11528.085946,5958.647329,22852.414689,60545.034784,13326.518029,55996.481734,931.052428,30037.415163,58321.904980,5756.015154,0.000000,37369.852142,8109.434177,6500.468141,36174.466671,16367.785468,36072.021331,9638.884983,0.000000,0.000000,1282.157595,17172.479484,5975.088515,0.0,2250.014452
77,Jubilee Hills,194414,17.430695,78.406081,14465.712338,178560.389821,0.0,6421.783267,2416.885646,33193.793008,50170.746074,13155.800214,27697.436846,2995.493421,24370.564377,61397.255384,2923.510841,820.280859,51513.015230,8991.464058,9802.280500,31614.934475,8938.499616,44959.300543,5946.694544,0.000000,4654.056355,8473.615458,10152.867282,6126.009828,0.0,0.000000
78,Banjara Hills,198169,17.416385,78.436884,14431.430012,105862.626933,0.0,15200.607657,0.000000,16494.033535,37953.461081,8146.230164,26596.279741,0.000000,13883.639624,37060.698333,2651.407212,2130.283513,33876.611304,6092.077424,2916.201113,17958.275815,15955.320557,107266.281859,1949.016073,0.000000,2067.683210,9049.523723,7360.860574,5093.329191,0.0,784.883104

In [52]:
new_df = new_df.reset_index(drop=True)
new_df

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,showroom,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.000000,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,0.0,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.000000,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.0,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.0,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,Nanakramguda,102581,17.416302,78.343114,13220.912950,11202.224985,0.0,0.000000,0.000000,2338.390996,3406.240690,3258.548690,8350.420658,3065.185507,6597.824915,6766.274936,0.000000,0.000000,755.685047,0.000000,6502.098538,3997.403907,0.000000,448.955479,2019.339611,0.000000,0.000000,532.505259,3863.653548,4297.943827,0.0,0.000000
67,Kokapet,155000,17.394735,78.337281,6986.081300,2500.368915,0.0,1066.522683,0.000000,3734.594509,0.000000,2618.143593,2439.805037,0.000000,1261.690863,2607.185224,0.000000,1885.631883,0.000000,0.000000,715.734402,1452.480213,2052.844928,0.000000,0.000000,0.000000,1813.895317,0.000000,5432.506584,0.000000,0.0,0.000000
68,Hitec City,158813,17.446384,78.376659,41486.304446,236694.068675,0.0,11528.085946,5958.647329,22852.414689,60545.034784,13326.518029,55996.481734,931.052428,30037.415163,58321.904980,5756.015154,0.000000,37369.852142,8109.434177,6500.468141,36174.466671,16367.785468,36072.021331,9638.884983,0.000000,0.000000,1282.157595,17172.479484,5975.088515,0.0,2250.014452
69,Jubilee Hills,194414,17.430695,78.406081,14465.712338,178560.389821,0.0,6421.783267,2416.885646,33193.793008,50170.746074,13155.800214,27697.436846,2995.493421,24370.564377,61397.255384,2923.510841,820.280859,51513.015230,8991.464058,9802.280500,31614.934475,8938.499616,44959.300543,5946.694544,0.000000,4654.056355,8473.615458,10152.867282,6126.009828,0.0,0.000000
70,Banjara Hills,198169,17.416385,78.436884,14431.430012,105862.626933,0.0,15200.607657,0.000000,16494.033535,37953.461081,8146.230164,26596.279741,0.000000,13883.639624,37060.698333,2651.407212,2130.283513,33876.611304,6092.077424,2916.201113,17958.275815,15955.320557,107266.281859,1949.016073,0.000000,2067.683210,9049.523723,7360.860574,5093.329191,0.0,784.883104

In [59]:
# new_df = new_df.drop(columns='showroom')
new_df

,Locality,Average Price,Latitude,Longitude,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,marketplace
0,Chevella,3462,17.313103,78.137523,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1744.302929,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Bhuvangiri,6483,17.505096,78.881987,0.000000,0.000000,0.0,0.000000,4713.355572,2570.691515,1261.277359,4992.838278,0.000000,0.000000,0.000000,0.000000,1119.744442,0.000000,7983.616491,0.000000,0.000000,0.000000,27670.627140,26106.333083,0.000000,0.000000,1320.153624,0.000000,1511.922662,0.000000,1230.027635
2,Shadnagar,8906,17.068916,78.207226,1589.557041,3016.276824,0.0,0.000000,0.000000,1399.188657,252.966541,3363.945128,307.698090,0.000000,0.000000,452.309920,0.000000,0.000000,1826.029178,282.440013,0.000000,0.000000,0.000000,4400.326045,11098.419346,1858.786022,303.854685,707.589610,0.000000,434.265481,0.000000
3,Ghatkesar,9770,17.452694,78.681166,3407.591043,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,646.930797,1512.309022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2528.387110,0.000000,0.000000,0.000000,0.000000,6412.694255,0.000000,0.000000
4,Maheshwaram,13268,17.134372,78.432225,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,Nanakramguda,102581,17.416302,78.343114,13220.912950,11202.224985,0.0,0.000000,0.000000,2338.390996,3406.240690,3258.548690,8350.420658,3065.185507,6597.824915,6766.274936,0.000000,0.000000,755.685047,0.000000,6502.098538,3997.403907,0.000000,448.955479,2019.339611,0.000000,0.000000,532.505259,3863.653548,4297.943827,0.000000
67,Kokapet,155000,17.394735,78.337281,6986.081300,2500.368915,0.0,1066.522683,0.000000,3734.594509,0.000000,2618.143593,2439.805037,0.000000,1261.690863,2607.185224,0.000000,1885.631883,0.000000,0.000000,715.734402,1452.480213,2052.844928,0.000000,0.000000,0.000000,1813.895317,0.000000,5432.506584,0.000000,0.000000
68,Hitec City,158813,17.446384,78.376659,41486.304446,236694.068675,0.0,11528.085946,5958.647329,22852.414689,60545.034784,13326.518029,55996.481734,931.052428,30037.415163,58321.904980,5756.015154,0.000000,37369.852142,8109.434177,6500.468141,36174.466671,16367.785468,36072.021331,9638.884983,0.000000,0.000000,1282.157595,17172.479484,5975.088515,2250.014452
69,Jubilee Hills,194414,17.430695,78.406081,14465.712338,178560.389821,0.0,6421.783267,2416.885646,33193.793008,50170.746074,13155.800214,27697.436846,2995.493421,24370.564377,61397.255384,2923.510841,820.280859,51513.015230,8991.464058,9802.280500,31614.934475,8938.499616,44959.300543,5946.694544,0.000000,4654.056355,8473.615458,10152.867282,6126.009828,0.000000
70,Banjara Hills,198169,17.416385,78.436884,14431.430012,105862.626933,0.0,15200.607657,0.000000,16494.033535,37953.461081,8146.230164,26596.279741,0.000000,13883.639624,37060.698333,2651.407212,2130.283513,33876.611304,6092.077424,2916.201113,17958.275815,15955.320557,107266.281859,1949.016073,0.000000,2067.683210,9049.523723,7360.860574,5093.329191,784.883104

In [68]:
import numpy as np
import pandas as pd

# Assuming df is your original DataFrame
df_extrapolated = pd.DataFrame()

def generate_random_values(center, num_points=160, scale=0.015):
    if np.isscalar(center):
        values = center + np.random.exponential(scale, num_points)
    else:
        values = np.array([c + np.random.exponential(scale, num_points) for c in center])
    return values.T  # Transpose the output

# Iterate over each row in the original DataFrame
for _, row in new_df.iterrows():
    # Repeat the 'Locality' column for each set of values
    locality_values = [row['Locality']] * 160

    # Generate random values for the row (excluding 'Locality', 'Latitude', 'Longitude')
    random_values = generate_random_values(row.drop(['Locality', 'Latitude', 'Longitude']))

    # Generate random Latitude and Longitude values within a radius
    latitude_values = generate_random_values(pd.Series([row['Latitude']]), num_points=160)
    longitude_values = generate_random_values(pd.Series([row['Longitude']]), num_points=160)

    # Create a DataFrame for the current row
    expanded_rows = pd.DataFrame(random_values, columns=row.drop(['Locality', 'Latitude', 'Longitude']).index)
    expanded_rows['Locality'] = locality_values
    expanded_rows['Latitude'] = latitude_values
    expanded_rows['Longitude'] = longitude_values

    # Append the current row to the extrapolated DataFrame
    df_extrapolated = pd.concat([df_extrapolated, expanded_rows], ignore_index=True)

# Display the extrapolated DataFrame
print(df_extrapolated)

        Average Price       parking     restaurant  fire_station  \
0         3461.989452     -0.001228      -0.002738     -0.005143
1         3461.990873      0.008124       0.010864      0.006972
2         3461.987961     -0.014165       0.004094     -0.008962
3         3461.985465      0.009461       0.002297     -0.014557
4         3461.995490      0.014694      -0.005821      0.007945
...               ...           ...            ...           ...
11355   198168.988577  14431.440597  105862.622831     -0.011109
11356   198169.009540  14431.433309  105862.622064      0.006073
11357   198168.992959  14431.437324  105862.632761      0.007844
11358   198169.004870  14431.429121  105862.626621      0.014212
11359   198169.006257  14431.440435  105862.617040      0.001202

             cinema   dentist        school           atm         fuel  \
0          0.000025  0.011098     -0.008541     -0.010881     0.008954
1          0.009906 -0.000586      0.011880      0.011326     0.010778
2          0.006022 -0.011658      0.013226      0.004525    -0.001419
3          0.006431  0.009453      0.008855     -0.000853    -0.006646
4          0.004588 -0.013690     -0.008849      0.001601     0.010481
...             ...       ...           ...           ...          ...
11355  15200.606743 -0.001161  16494.041153  37953.457181  8146.245130
11356  15200.610727 -0.005140  16494.045153  37953.472184  8146.231776
11357  15200.613883  0.005234  16494.039854  37953.460543  8146.223418
11358  15200.611976  0.001724  16494.040444  37953.475769  8146.241841
11359  15200.599545 -0.013082  16494.046328  37953.467313  8146.244480

          fast_food   toilets      pharmacy          bank       police  \
0          0.000843 -0.009114     -0.004705      0.001864     0.010458
1          0.005465 -0.007376      0.005202      0.003054     0.013546
2          0.000725 -0.001994     -0.005656      0.003241    -0.000688
3         -0.005788 -0.007765     -0.002428     -0.011040    -0.012050
4         -0.002901  0.014476     -0.013303      0.012835     0.006446
...             ...       ...           ...           ...          ...
11355  26596.267568 -0.010431  13883.642780  37060.687355  2651.414237
11356  26596.286219  0.012594  13883.649977  37060.687201  2651.404318
11357  26596.286001 -0.004482  13883.630421  37060.688298  2651.421705
11358  26596.268929  0.012501  13883.647424  37060.686422  2651.405760
11359  26596.290122  0.001346  13883.645205  37060.694310  2651.409366

          post_box  place_of_worship          bar          pub          cafe  \
0         0.000751          0.012298     0.010657    -0.005068      0.012321
1        -0.007412          0.000352     0.001531    -0.003675      0.014484
2         0.011737          0.006877     0.004492     0.004456      0.002425
3        -0.010606          0.013773     0.012874    -0.008298     -0.009866
4        -0.009725         -0.004807    -0.007403     0.005791      0.003965
...            ...               ...          ...          ...           ...
11355  2130.274312      33876.625579  6092.070593  2916.188602  17958.283059
11356  2130.297832      33876.616477  6092.079555  2916.206597  17958.284906
11357  2130.277099      33876.602826  6092.076884  2916.192764  17958.263919
11358  2130.291471      33876.602594  6092.068469  2916.193609  17958.263197
11359  2130.291561      33876.625153  6092.083613  2916.206308  17958.281528

             clinic       hospital  community_centre  vending_machine  \
0         -0.010364    1744.311680         -0.013537        -0.000936
1          0.006083    1744.289818          0.012065         0.007551
2         -0.007282    1744.299518         -0.002921         0.009468
3          0.013522    1744.305074         -0.006494         0.008406
4         -0.000154    1744.313505          0.013626        -0.006272
...             ...            ...               ...              ...
11355  15955.330287  107266.285259       1949.026511         0.011539
11356  15955.311381  107266.268268       1949.011716         0.002869
11357  15955.331712  107266.291387       1949.005171        -0.008774
11358  15955.333416  107266.278527       1949.019913        -0.014707
11359  15955.306339  107266.267997       1949.013329        -0.014792

       bus_station  health_post      college      theatre  marketplace  \
0        -0.013797     0.010241     0.007958     0.010391    -0.002424
1        -0.004203    -0.012195     0.014034     0.003958    -0.006272
2         0.005861     0.010245     0.002252     0.003792    -0.013570
3         0.011385     0.003049    -0.013258     0.011260     0.009435
4        -0.000107     0.002980     0.006469     0.009152    -0.006133
...            ...          ...          ...          ...          ...
11355  2067.687173  9049.527429  7360.863899  5093.319492   784.883202
11356  2067.685678  9049.508855  7360.870439  5093.328836   784.879566
11357  2067.682242  9049.532121  7360.875273  5093.322961   784.895835
11358  2067.694381  9049.513657  7360.865148  5093.333106   784.895028
11359  2067.687220  9049.517384  7360.868269  5093.340934   784.872943

            Locality   Latitude  Longitude
0           Chevella  17.322011  78.124018
1           Chevella  17.308007  78.125248
2           Chevella  17.314100  78.129774
3           Chevella  17.302859  78.132181
4           Chevella  17.322623  78.149956
...              ...        ...        ...
11355  Banjara Hills  17.426625  78.444911
11356  Banjara Hills  17.412021  78.442968
11357  Banjara Hills  17.414005  78.441009
11358  Banjara Hills  17.418988  78.450364
11359  Banjara Hills  17.407489  78.441058

[11360 rows x 31 columns]

In [70]:
new_df = df_extrapolated
new_df

,Average Price,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,marketplace,Locality,Latitude,Longitude
0,3461.989452,-0.001228,-0.002738,-0.005143,0.000025,0.011098,-0.008541,-0.010881,0.008954,0.000843,-0.009114,-0.004705,0.001864,0.010458,0.000751,0.012298,0.010657,-0.005068,0.012321,-0.010364,1744.311680,-0.013537,-0.000936,-0.013797,0.010241,0.007958,0.010391,-0.002424,Chevella,17.322011,78.124018
1,3461.990873,0.008124,0.010864,0.006972,0.009906,-0.000586,0.011880,0.011326,0.010778,0.005465,-0.007376,0.005202,0.003054,0.013546,-0.007412,0.000352,0.001531,-0.003675,0.014484,0.006083,1744.289818,0.012065,0.007551,-0.004203,-0.012195,0.014034,0.003958,-0.006272,Chevella,17.308007,78.125248
2,3461.987961,-0.014165,0.004094,-0.008962,0.006022,-0.011658,0.013226,0.004525,-0.001419,0.000725,-0.001994,-0.005656,0.003241,-0.000688,0.011737,0.006877,0.004492,0.004456,0.002425,-0.007282,1744.299518,-0.002921,0.009468,0.005861,0.010245,0.002252,0.003792,-0.013570,Chevella,17.314100,78.129774
3,3461.985465,0.009461,0.002297,-0.014557,0.006431,0.009453,0.008855,-0.000853,-0.006646,-0.005788,-0.007765,-0.002428,-0.011040,-0.012050,-0.010606,0.013773,0.012874,-0.008298,-0.009866,0.013522,1744.305074,-0.006494,0.008406,0.011385,0.003049,-0.013258,0.011260,0.009435,Chevella,17.302859,78.132181
4,3461.995490,0.014694,-0.005821,0.007945,0.004588,-0.013690,-0.008849,0.001601,0.010481,-0.002901,0.014476,-0.013303,0.012835,0.006446,-0.009725,-0.004807,-0.007403,0.005791,0.003965,-0.000154,1744.313505,0.013626,-0.006272,-0.000107,0.002980,0.006469,0.009152,-0.006133,Chevella,17.322623,78.149956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11355,198168.988577,14431.440597,105862.622831,-0.011109,15200.606743,-0.001161,16494.041153,37953.457181,8146.245130,26596.267568,-0.010431,13883.642780,37060.687355,2651.414237,2130.274312,33876.625579,6092.070593,2916.188602,17958.283059,15955.330287,107266.285259,1949.026511,0.011539,2067.687173,9049.527429,7360.863899,5093.319492,784.883202,Banjara Hills,17.426625,78.444911
11356,198169.009540,14431.433309,105862.622064,0.006073,15200.610727,-0.005140,16494.045153,37953.472184,8146.231776,26596.286219,0.012594,13883.649977,37060.687201,2651.404318,2130.297832,33876.616477,6092.079555,2916.206597,17958.284906,15955.311381,107266.268268,1949.011716,0.002869,2067.685678,9049.508855,7360.870439,5093.328836,784.879566,Banjara Hills,17.412021,78.442968
11357,198168.992959,14431.437324,105862.632761,0.007844,15200.613883,0.005234,16494.039854,37953.460543,8146.223418,26596.286001,-0.004482,13883.630421,37060.688298,2651.421705,2130.277099,33876.602826,6092.076884,2916.192764,17958.263919,15955.331712,107266.291387,1949.005171,-0.008774,2067.682242,9049.532121,7360.875273,5093.322961,784.895835,Banjara Hills,17.414005,78.441009
11358,198169.004870,14431.429121,105862.626621,0.014212,15200.611976,0.001724,16494.040444,37953.475769,8146.241841,26596.268929,0.012501,13883.647424,37060.686422,2651.405760,2130.291471,33876.602594,6092.068469,2916.193609,17958.263197,15955.333416,107266.278527,1949.019913,-0.014707,2067.694381,9049.513657,7360.865148,5093.333106,784.895028,Banjara Hills,17.418988,78.450364
11359,198169.006257,14431.440435,105862.617040,0.001202,15200.599545,-0.013082,16494.046328,37953.467313,8146.244480,26596.290122,0.001346,13883.645205,37060.694310,2651.409366,2130.291561,33876.625153,6092.083613,2916.206308,17958.281528,15955.306339,107266.267997,1949.013329,-0.014792,2067.687220,9049.517384,7360.868269,5093.340934,784.872943,Banjara Hills,17.407489,78.441058

In [71]:
new_df = new_df.drop(columns='Locality')
new_df

,Average Price,parking,restaurant,fire_station,cinema,dentist,school,atm,fuel,fast_food,toilets,pharmacy,bank,police,post_box,place_of_worship,bar,pub,cafe,clinic,hospital,community_centre,vending_machine,bus_station,health_post,college,theatre,marketplace,Latitude,Longitude
0,3461.989452,-0.001228,-0.002738,-0.005143,0.000025,0.011098,-0.008541,-0.010881,0.008954,0.000843,-0.009114,-0.004705,0.001864,0.010458,0.000751,0.012298,0.010657,-0.005068,0.012321,-0.010364,1744.311680,-0.013537,-0.000936,-0.013797,0.010241,0.007958,0.010391,-0.002424,17.322011,78.124018
1,3461.990873,0.008124,0.010864,0.006972,0.009906,-0.000586,0.011880,0.011326,0.010778,0.005465,-0.007376,0.005202,0.003054,0.013546,-0.007412,0.000352,0.001531,-0.003675,0.014484,0.006083,1744.289818,0.012065,0.007551,-0.004203,-0.012195,0.014034,0.003958,-0.006272,17.308007,78.125248
2,3461.987961,-0.014165,0.004094,-0.008962,0.006022,-0.011658,0.013226,0.004525,-0.001419,0.000725,-0.001994,-0.005656,0.003241,-0.000688,0.011737,0.006877,0.004492,0.004456,0.002425,-0.007282,1744.299518,-0.002921,0.009468,0.005861,0.010245,0.002252,0.003792,-0.013570,17.314100,78.129774
3,3461.985465,0.009461,0.002297,-0.014557,0.006431,0.009453,0.008855,-0.000853,-0.006646,-0.005788,-0.007765,-0.002428,-0.011040,-0.012050,-0.010606,0.013773,0.012874,-0.008298,-0.009866,0.013522,1744.305074,-0.006494,0.008406,0.011385,0.003049,-0.013258,0.011260,0.009435,17.302859,78.132181
4,3461.995490,0.014694,-0.005821,0.007945,0.004588,-0.013690,-0.008849,0.001601,0.010481,-0.002901,0.014476,-0.013303,0.012835,0.006446,-0.009725,-0.004807,-0.007403,0.005791,0.003965,-0.000154,1744.313505,0.013626,-0.006272,-0.000107,0.002980,0.006469,0.009152,-0.006133,17.322623,78.149956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11355,198168.988577,14431.440597,105862.622831,-0.011109,15200.606743,-0.001161,16494.041153,37953.457181,8146.245130,26596.267568,-0.010431,13883.642780,37060.687355,2651.414237,2130.274312,33876.625579,6092.070593,2916.188602,17958.283059,15955.330287,107266.285259,1949.026511,0.011539,2067.687173,9049.527429,7360.863899,5093.319492,784.883202,17.426625,78.444911
11356,198169.009540,14431.433309,105862.622064,0.006073,15200.610727,-0.005140,16494.045153,37953.472184,8146.231776,26596.286219,0.012594,13883.649977,37060.687201,2651.404318,2130.297832,33876.616477,6092.079555,2916.206597,17958.284906,15955.311381,107266.268268,1949.011716,0.002869,2067.685678,9049.508855,7360.870439,5093.328836,784.879566,17.412021,78.442968
11357,198168.992959,14431.437324,105862.632761,0.007844,15200.613883,0.005234,16494.039854,37953.460543,8146.223418,26596.286001,-0.004482,13883.630421,37060.688298,2651.421705,2130.277099,33876.602826,6092.076884,2916.192764,17958.263919,15955.331712,107266.291387,1949.005171,-0.008774,2067.682242,9049.532121,7360.875273,5093.322961,784.895835,17.414005,78.441009
11358,198169.004870,14431.429121,105862.626621,0.014212,15200.611976,0.001724,16494.040444,37953.475769,8146.241841,26596.268929,0.012501,13883.647424,37060.686422,2651.405760,2130.291471,33876.602594,6092.068469,2916.193609,17958.263197,15955.333416,107266.278527,1949.019913,-0.014707,2067.694381,9049.513657,7360.865148,5093.333106,784.895028,17.418988,78.450364
11359,198169.006257,14431.440435,105862.617040,0.001202,15200.599545,-0.013082,16494.046328,37953.467313,8146.244480,26596.290122,0.001346,13883.645205,37060.694310,2651.409366,2130.291561,33876.625153,6092.083613,2916.206308,17958.281528,15955.306339,107266.267997,1949.013329,-0.014792,2067.687220,9049.517384,7360.868269,5093.340934,784.872943,17.407489,78.441058

In [72]:
new_df.to_csv('training_data.csv')